language: node_js
node_js:
  - "lts/*"
services:
  - mongodb
before_script:
  - sleep 15
  - mongo admin --eval 'db.createUser({user:"xbsdb",pwd:"xbsdbpass",roles:[{role:"root",db:"admin"}]});'
  - mongo xbrowsersynctest --host localhost --port 27017 --username xbsdb --password xbsdbpass --authenticationDatabase admin --eval 'db.bookmarks.count({})'
install:
  - npm install
script:
  - npm run build
  - npm run coverage
  - npm run e2etests