language: node_js
node_js:
  - "lts/*"
services:
  - mongodb
before_script:
  - sleep 15
  - mongo admin --eval 'db.createUser({user:"xbsdb",pwd:"xbsdbpass",roles:[{role:"root",db:"admin"}]});'
install:
  - npm install
script:
  - npm run build
  - npm run coverage
  - npm run e2etests